### ISSUE TITLE
Failed to validate substatus above 1000

### ISSUE THREAD

**Issue by ainopara** [daydreaming666/Amenoma#41]
```
[   INFO] 2022-09-03 18:42:31,584 /    UIMain[943]	/Detected info: {'equipped': '宗室之晷', 'level': '+20', 'main_attr_name': '生命值', 'main_attr_value': '46.6%', 'name': '角斗士的希冀', 'subattr_1': '暴击伤害+7.8%', 'subattr_2': '元素精通+40', 'subattr_3': '生命值+1,005', 'subattr_4': '暴击率+7.0%', 'type': '时之沙', 'star': 5, 'locked': True}
[   INFO] 2022-09-03 18:42:31,584 /    UIMain[368]	/Info message shown. msg=识别到 [角斗士的希冀]
[  ERROR] 2022-09-03 18:42:31,588 / art_saver[145]	/Save Artifact failed: bad sub stat value
[  ERROR] 2022-09-03 18:42:31,588 / art_saver[207]	/Artifact attributes are not valid
Traceback (most recent call last):
  File "art_saver.py", line 202, in add
  File "art_saver.py", line 135, in __init__
AssertionError: Artifact attributes are not valid
[WARNING] 2022-09-03 18:42:31,589 /    UIMain[914]	/[ArtifactDB] Failed to save a Artifact. id: 106 detected info: {'equipped': '', 'level': '+20', 'main_attr_name': '生命值', 'main_attr_value': '46.6%', 'name': '角斗士的希冀', 'subattr_1': '暴击伤害+7.8%', 'subattr_2': '元素精通+40', 'subattr_3': '生命值+1,005', 'subattr_4': '暴击率+7.0%', 'type': '时之沙', 'star': 5, 'locked': True, 'setid': 4}
[  ERROR] 2022-09-03 18:42:31,589 /    UIMain[374]	/Error message shown. msg=数值验证失败
```

**Comment by daydreaming666** [comment]
```
......  'subattr_3': '生命值+1,005' ......
```
这里识别到的生命值+1,005是无效的数值（因为可能的数值的组合209/239/269/299不可能组合出1005），所以对识别结果做了过滤

**Comment by ainopara** [comment]
了解了，这件圣遗物实际上是生命值+1,105
这种识别错误导致圣遗物被过滤掉的情况，似乎不会生成截图。
不知道截图发到这里是否有助于提高识别的准确度？

**Comment by daydreaming666** [comment]
不会提高。模型的训练基于随机生成的词条图片，而非实际的圣遗物截图。

> 这种识别错误导致圣遗物被过滤掉的情况，似乎不会生成截图。
考虑之后的版本进行优化，在发生这种错误时截图保存
