### ISSUE TITLE
“导出所有格式的json文件”还是有问题

### ISSUE THREAD

**Issue by oTnTh** [daydreaming666/Amenoma#42]
v3.0.2，不选中“导出所有格式的json文件”可以完成扫描，选中后报错：

```
[   INFO] 2022-09-13 05:20:21,005 /    UIMain[368]	/Info message shown. msg=扫描: 1480
[   INFO] 2022-09-13 05:20:21,005 /    UIMain[368]	/Info message shown. msg=  - 保存: 1374
[   INFO] 2022-09-13 05:20:21,005 /    UIMain[368]	/Info message shown. msg=  - 失败: 0
[   INFO] 2022-09-13 05:20:21,006 /    UIMain[368]	/Info message shown. msg=  - 跳过: 106
[  ERROR] 2022-09-13 05:20:24,441 /    UIMain[980]	/string indices must be integers
Traceback (most recent call last):
  File "UIMain.py", line 974, in scanArts
  File "UIMain.py", line 974, in <lambda>
  File "art_saver.py", line 250, in exportGenshinArtJSON
TypeError: string indices must be integers
[   INFO] 2022-09-13 05:20:24,441 /    UIMain[368]	/Info message shown. msg=扫描已中断
[  ERROR] 2022-09-13 05:20:24,486 /    UIMain[374]	/Error message shown. msg=TypeError('string indices must be integers')
[   INFO] 2022-09-13 05:20:24,488 /    UIMain[368]	/Info message shown. msg=导出出错，已停止
[   INFO] 2022-09-13 05:20:24,492 /    UIMain[368]	/Info message shown. msg=扫描: 1480
[   INFO] 2022-09-13 05:20:24,492 /    UIMain[368]	/Info message shown. msg=  - 保存: 1374
[   INFO] 2022-09-13 05:20:24,493 /    UIMain[368]	/Info message shown. msg=  - 失败: 0
[   INFO] 2022-09-13 05:20:24,493 /    UIMain[368]	/Info message shown. msg=  - 跳过: 106
[   INFO] 2022-09-13 05:20:24,493 /    UIMain[368]	/Info message shown. msg=失败结果将存储至 artifacts 文件夹
[   INFO] 2022-09-13 05:20:24,493 /    UIMain[368]	/Info message shown. msg=星级: (保存 / 扫描)
[   INFO] 2022-09-13 05:20:24,494 /    UIMain[368]	/Info message shown. msg=5: 1030 / 1030
[   INFO] 2022-09-13 05:20:24,494 /    UIMain[368]	/Info message shown. msg=4: 344 / 344
[   INFO] 2022-09-13 05:20:24,494 /    UIMain[368]	/Info message shown. msg=3: 0 / 37
[   INFO] 2022-09-13 05:20:24,494 /    UIMain[368]	/Info message shown. msg=2: 0 / 32
[   INFO] 2022-09-13 05:20:24,495 /    UIMain[368]	/Info message shown. msg=1: 0 / 37

```

**Comment by zzzqh** [comment]
[   INFO] 2023-01-27 16:21:35,348 /    UIMain[368]	/Info message shown. msg=[强化材料] 已跳过
[  ERROR] 2023-01-27 16:21:39,339 /    UIMain[980]	/string indices must be integers
Traceback (most recent call last):
  File "UIMain.py", line 974, in scanArts
  File "UIMain.py", line 974, in <lambda>
  File "art_saver.py", line 250, in exportGenshinArtJSON
TypeError: string indices must be integers
[   INFO] 2023-01-27 16:21:39,340 /    UIMain[368]	/Info message shown. msg=扫描已完成
[  ERROR] 2023-01-27 16:21:39,342 /    UIMain[374]	/Error message shown. msg=TypeError('string indices must be integers')
[   INFO] 2023-01-27 16:21:39,439 /    UIMain[368]	/Info message shown. msg=导出出错，已停止
[   INFO] 2023-01-27 16:21:39,440 /    UIMain[368]	/Info message shown. msg=扫描: 1427
[   INFO] 2023-01-27 16:21:39,441 /    UIMain[368]	/Info message shown. msg=  - 保存: 1336
[   INFO] 2023-01-27 16:21:39,442 /    UIMain[368]	/Info message shown. msg=  - 失败: 0
[   INFO] 2023-01-27 16:21:39,443 /    UIMain[368]	/Info message shown. msg=  - 跳过: 91
[   INFO] 2023-01-27 16:21:39,444 /    UIMain[368]	/Info message shown. msg=失败结果将存储至 artifacts 文件夹
[   INFO] 2023-01-27 16:21:39,444 /    UIMain[368]	/Info message shown. msg=星级: (保存 / 扫描)
[   INFO] 2023-01-27 16:21:39,444 /    UIMain[368]	/Info message shown. msg=5: 1336 / 1336
[   INFO] 2023-01-27 16:21:39,445 /    UIMain[368]	/Info message shown. msg=4: 0 / 46
[   INFO] 2023-01-27 16:21:39,445 /    UIMain[368]	/Info message shown. msg=3: 0 / 45
[   INFO] 2023-01-27 16:21:39,445 /    UIMain[368]	/Info message shown. msg=2: 0 / 0
[   INFO] 2023-01-27 16:21:39,446 /    UIMain[368]	/Info message shown. msg=1: 0 / 0

3.4同样遇到这个问题
